# Generated by Django 5.1.2 on 2024-11-06 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='last_reset_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
