# Generated by Django 5.1.2 on 2024-11-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_billreminder_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billreminder',
            name='recurring_interval',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('weekly', 'Weekly'), ('yearly', 'Yearly'), ('one_time', 'One-Time')], default='monthly', max_length=20),
        ),
    ]
